name: Update RSS and Build HTML

on:
  schedule:
    - cron: '0 * * * *'  # chạy mỗi giờ
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Cài thư viện Python
        run: pip install feedparser

      - name: Chạy script lấy tin
        run: python rss_to_html.py

      - name: Deploy lên Netlify
        uses: nwtgck/actions-netlify@v1.1.4
        with:
          publish-dir: ./public
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
